### ISSUE TITLE
Refactor to TypeScript

### ISSUE THREAD

**Issue by linonetwo** [laobubu/HyperMD#6]
Do you need a refactoring to TypeScript?

Seems you are a TypeScript user too, I'm willing to PR if you need it.

**Comment by laobubu** [comment]
Rewriting with TypeScript will definitely improve the developing experience
if there is a fully completed CodeMirror d.ts.

Besides, it takes lots of time and effort to refractor and adjust so that
CodeMirror can load HyperMD easily.

To be honest, the hardest part of developing HyperMD is to understand
CodeMirror and implement ideas under CodeMirror's game rules. TypeScript's
goodies can help a lot but not worthy enough.

Sorry for replying so late.

2017年3月23日星期四，lin onetwo <notifications@github.com> 写道：

**Comment by linonetwo** [comment]
Seems a hard work, maybe summer vacation...

**Comment by laobubu** [comment]
Finally moved to TypeScript ( #21 ). Fed up with ES5
